@startuml
set separator none
title Bounded Contexts (Containers) - Parking System

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Operator, "Operator", $descr="Responsible for managing entries, exits, and incident registration.", $tags="", $link="")

System_Boundary("ParkingSystem_boundary", "Parking System", $tags="") {
  Container(ParkingSystem.AccessControl, "Access Control", $techn="Java / Spring Boot", $descr="Manages entries, exits, and vehicle/owner registration.", $tags="", $link="")
  Container(ParkingSystem.Payment, "Payment", $techn="External API / Payment Gateway", $descr="Processes payments for ticket validations and monthly passes.", $tags="", $link="")
  Container(ParkingSystem.Incident, "Incident", $techn="Java / Spring Boot", $descr="Registers and tracks incidents (e.g., vehicle damage).", $tags="", $link="")
}

Rel(ParkingSystem.AccessControl, ParkingSystem.Payment, "Validates if payment has been made to end ticket lifecycle", $techn="", $tags="", $link="")
Rel(Operator, ParkingSystem.AccessControl, "Registers vehicles and owners, grants entry by generating tickets lifecycle", $techn="", $tags="", $link="")
Rel(Operator, ParkingSystem.Incident, "Registers incidents about user experience or vehicles damage.", $techn="", $tags="", $link="")
Rel(ParkingSystem.Incident, ParkingSystem.Payment, "Payment operation for compensations", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml